### ISSUE TITLE
Adding new device on custom instance crashes app

### ISSUE THREAD

**Issue by nielscil** [anonaddy/addy-android#4]
**Describe the bug**
When settings up a new device with an api token, the app crashes after scanning the QR code. When opening again the setup process starts again.

**To Reproduce**
1. Open freshly installed app from play store.
2. Click on Get Started.
3. Scan QR code.
4. Crash.

**Logs from the app**
Store logs won't work in setup, so I got to logcat. This is the error when crashing, but 

`2024-11-17 09:15:08.472 18138-18138/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: host.stjin.anonaddy, PID: 18138
    java.lang.NullPointerException: fromJson(...) must not be null
        at host.stjin.anonaddy_shared.AddyIoApp.getUserResource(AddyIoApp.kt:18)
        at host.stjin.anonaddy.ui.setup.AddApiBottomDialogFragment$verifyApiKey$1.invokeSuspend$lambda$0(AddApiBottomDialogFragment.kt:327)
        at host.stjin.anonaddy.ui.setup.AddApiBottomDialogFragment$verifyApiKey$1.$r8$lambda$GdOmuWJJNl7osMna3iAV9UIixII(Unknown Source:0)
        at host.stjin.anonaddy.ui.setup.AddApiBottomDialogFragment$verifyApiKey$1$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
        at host.stjin.anonaddy_shared.NetworkHelper.verifyApiKey(NetworkHelper.kt:589)
        at host.stjin.anonaddy_shared.NetworkHelper$verifyApiKey$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
        at android.os.Handler.handleCallback(Handler.java:959)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loopOnce(Looper.java:232)
        at android.os.Looper.loop(Looper.java:317)
        at android.app.ActivityThread.main(ActivityThread.java:8597)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5de169e, Dispatchers.Main.immediate]`

**Expected behavior**
Login new device in

**Smartphone (please complete the following information):**
 - Device: Oneplus 12  / Oneplus 7T Pro
 - OS: Android 15 / android 14
 - Browser -
 - Version v5.4.1

**Additional context**
I was testing PR https://github.com/anonaddy/anonaddy/pull/695 but even after reverting to default docker image, the issue persists.

**Comment by Stjin** [comment]
Thanks for the report! Rooky mistake on my part. I have fixed it immediately!
